#ifndef __URI_H__
#define __URI_H__

#include <unordered_map>
#include <string>

enum class Uri 
{
    dcap,
    sdev,
    edev,
    edev_list,
    rg,
    dstat,
    fsa,
    fsa_list,
    sub,
    sub_list,
    ntfy,
    ntfy_list,
    rsps,
    rsps_list,
    rsp,
    rsp_list,
    tm,
    di,
    loc,
    loc_list,
    ps,
    ns,
    ns_list,
    addr,
    addr_list,
    rpl,
    rpl_list,
    srt,
    srt_list,
    ll,
    ll_list,
    nbh,
    nbh_list,
    lel,
    lel_list,
    cfg,
    prcfg,
    prcfg_list,
    file,
    file_list,
    fs,
    dr,
    dr_list,
    actedc,
    actedc_list,
    edc,
    edc_list,
    lsl,
    lsl_list,
    upt,
    upt_list,
    mr,
    mr_list,
    rt,
    rs,
    rs_list,
    r,
    r_list,
    mup,
    mup_list,
    tp,
    tp_list,
    rc,
    rc_list,
    acttti,
    acttti_list,
    tti,
    tti_list,
    cti,
    cti_list,
    msg,
    msg_list,
    acttxt,
    acttxt_list,
    txt,
    txt_list,
    bill,
    bill_list,
    ca,
    ca_list,
    actbp,
    actbp_list,
    bp,
    bp_list,
    pro,
    pro_list,
    brs,
    brs_list,
    br,
    br_list,
    tar,
    tar_list,
    ver,
    ver_list,
    ss,
    ppy,
    ppy_list,
    ab,
    os,
    actsi,
    actsi_list,
    si,
    si_list,
    cr,
    cr_list,
    frq,
    frq_list,
    frp,
    frp_list,
    der,
    der_list,
    aupt,
    derp,
    derp_list,
    cdp,
    derp,
    derp_list,
    derg,
    ders,
    dera,
    dercap,
    actderc,
    actderc_list,
    derc,
    derc_list,
    dderc,
    dc,
    dc_list
};

static std::unordered_map <std::string, Uri> uri_map = 
{
    {"/dcap", Uri::dcap},
    {"/sdev", Uri::sdev},
    {"/edev", Uri::edev},
    {"/rg", Uri::rg},
    {"/dstat", Uri::dstat},
    {"/fsa", Uri::fsa},
    {"/sub", Uri::sub},
    {"/ntfy", Uri::ntfy},
    {"/rsps", Uri::rsps},
    {"/rsp", Uri::rsp},
    {"/tm", Uri::tm},
    {"/di", Uri::di},
    {"/loc", Uri::loc},
    {"/ps", Uri::ns},
    {"/addr", Uri::addr},
    {"/rpl", Uri::srt},
    {"/ll", Uri::ll},
    {"/nbh", Uri::nbh},
    {"/lel", Uri::lel},
    {"/cfg", Uri::cfg},
    {"/prcfg", Uri::prcfg},
    {"/file", Uri::file},
    {"/fs", Uri::dr},
    {"/actedc", Uri::actedc},
    {"/edc", Uri::edc},
    {"/lsl", Uri::lsl},
    {"/upt", Uri::upt},
    {"/mr", Uri::mr},
    {"/rt", Uri::rt},
    {"/rs", Uri::rs},
    {"/r", Uri::r},
    {"/mup", Uri::mup},
    {"/tp", Uri::tp},
    {"/rc", Uri::rc},
    {"/acttti", Uri::acttti},
    {"/tti", Uri::tti},
    {"/cti", Uri::cti},
    {"/msg", Uri::msg},
    {"/acttxt", Uri::acttxt},
    {"/txt", Uri::txt},
    {"/bill", Uri::bill},
    {"/ca", Uri::ca},
    {"/actbp", Uri::actbp},
    {"/bp", Uri::bp},
    {"/pro", Uri::pro},
    {"/brs", Uri::brs},
    {"/br", Uri::br},
    {"/tar", Uri::tar},
    {"/ver", Uri::ver},
    {"/ss", Uri::ss},
    {"/ppy", Uri::ppy},
    {"/ab", Uri::ab},
    {"/os", Uri::os},
    {"/actsi", Uri::actsi},
    {"/si", Uri::si},
    {"/cr", Uri::cr},
    {"/frq", Uri::frq},
    {"/frp", Uri::frp},
    {"/der", Uri::der},
    {"/aupt", Uri::aupt},
    {"/derp", Uri::derp},
    {"/cdp", Uri::cdp},
    {"/derg", Uri::derg},
    {"/ders", Uri::ders},
    {"/dera", Uri::dera},
    {"/dercap", Uri::dercap},
    {"/actderc", Uri::actderc},
    {"/derc", Uri::derc},
    {"/dderc", Uri::dderc},
    {"/dc", Uri::dc}
};

#endif // __URI_H__