#ifndef __URI_H__
#define __URI_H__

#include <unordered_map>
#include <string>

enum class Uri 
{
    dcap,
    sdev,
    edev,
    edev_list,
    rg,
    dstat,
    fsa,
    fsa_list,
    sub,
    sub_list,
    ntfy,
    ntfy_list,
    rsps,
    rsps_list,
    rsp,
    rsp_list,
    tm,
    di,
    loc,
    loc_list,
    ps,
    ns,
    ns_list,
    addr,
    addr_list,
    rpl,
    rpl_list,
    srt,
    srt_list,
    ll,
    ll_list,
    nbh,
    nbh_list,
    lel,
    lel_list,
    cfg,
    prcfg,
    prcfg_list,
    file,
    file_list,
    fs,
    dr,
    dr_list,
    actedc,
    actedc_list,
    edc,
    edc_list,
    lsl,
    lsl_list,
    upt,
    upt_list,
    mr,
    mr_list,
    rt,
    rs,
    rs_list,
    r,
    r_list,
    mup,
    mup_list,
    tp,
    tp_list,
    rc,
    rc_list,
    acttti,
    acttti_list,
    tti,
    tti_list,
    cti,
    cti_list,
    msg,
    msg_list,
    acttxt,
    acttxt_list,
    txt,
    txt_list,
    bill,
    bill_list,
    ca,
    ca_list,
    actbp,
    actbp_list,
    bp,
    bp_list,
    pro,
    pro_list,
    brs,
    brs_list,
    br,
    br_list,
    tar,
    tar_list,
    ver,
    ver_list,
    ss,
    ppy,
    ppy_list,
    ab,
    os,
    actsi,
    actsi_list,
    si,
    si_list,
    cr,
    cr_list,
    frq,
    frq_list,
    frp,
    frp_list,
    der,
    der_list,
    aupt,
    derp,
    derp_list,
    cdp,
    derg,
    ders,
    dera,
    dercap,
    actderc,
    actderc_list,
    derc,
    derc_list,
    dderc,
    dc,
    dc_list
};

static std::unordered_map <std::string, Uri> uri_map = 
{
    {"/dcap", Uri::dcap},
    {"/sdev", Uri::sdev},
    {"/edev/*", Uri::edev},
    {"/edev", Uri::edev_list},
    {"/rg", Uri::rg},
    {"/dstat", Uri::dstat},
    {"/fsa/*", Uri::fsa},
    {"/fsa", Uri::fsa_list},
    {"/sub/*", Uri::sub},
    {"/sub", Uri::sub_list},
    {"/ntfy/*", Uri::ntfy},
    {"/ntfy", Uri::ntfy_list},
    {"/rsps/*", Uri::rsps},
    {"/rsps", Uri::rsps_list},
    {"/rsp/*", Uri::rsp},
    {"/rsp", Uri::rsp_list},
    {"/tm", Uri::tm},
    {"/di", Uri::di},
    {"/loc/*", Uri::loc_list},
    {"/loc", Uri::loc},
    {"/ns/*", Uri::ns},
    {"/ns", Uri::ns_list},
    {"/addr/*", Uri::addr},
    {"/addr", Uri::addr_list},
    {"/rpl/*", Uri::rpl},
    {"/rpl", Uri::rpl_list},
    {"/srt/*", Uri::srt},
    {"/srt", Uri::srt_list},
    {"/ll/*", Uri::ll},
    {"/ll", Uri::ll_list},
    {"/nbh/*", Uri::nbh},
    {"/nbh", Uri::nbh_list},
    {"/lel/*", Uri::lel},
    {"/lel", Uri::lel_list},
    {"/cfg", Uri::cfg},
    {"/prcfg/*", Uri::prcfg},
    {"/prcfg", Uri::prcfg_list},
    {"/file/*", Uri::file},
    {"/file", Uri::file_list},
    {"/fs", Uri::dr},
    {"/dr/*", Uri::dr},
    {"/dr", Uri::dr_list},
    {"/actedc/*", Uri::actedc},
    {"/actedc", Uri::actedc_list},
    {"/edc/*", Uri::edc},
    {"/edc", Uri::edc_list},
    {"/lsl/*", Uri::lsl},
    {"/lsl", Uri::lsl_list},
    {"/upt/*", Uri::upt_list},
    {"/upt", Uri::upt},
    {"/mr/*", Uri::mr_list},
    {"/mr", Uri::mr},
    {"/rt", Uri::rt},
    {"/rs/*", Uri::rs},
    {"/rs", Uri::rs_list},
    {"/r/*", Uri::r},
    {"/r", Uri::r_list},
    {"/mup/*", Uri::mup},
    {"/mup", Uri::mup_list},
    {"/tp/*", Uri::tp},
    {"/tp", Uri::tp_list},
    {"/rc/*", Uri::rc},
    {"/rc", Uri::rc_list},
    {"/acttti/*", Uri::acttti},
    {"/acttti", Uri::acttti_list},
    {"/tti/*", Uri::tti},
    {"/tti", Uri::tti_list},
    {"/cti/*", Uri::cti},
    {"/cti", Uri::cti_list},
    {"/msg/*", Uri::msg},
    {"/msg", Uri::msg_list},
    {"/acttxt/*", Uri::acttxt},
    {"/acttxt", Uri::acttxt_list},
    {"/txt/*", Uri::txt},
    {"/txt", Uri::txt_list},
    {"/bill/*", Uri::bill},
    {"/bill", Uri::bill_list},
    {"/ca/*", Uri::ca},
    {"/ca", Uri::ca_list},
    {"/actbp/*", Uri::actbp},
    {"/actbp", Uri::actbp_list},
    {"/bp/*", Uri::bp},
    {"/bp", Uri::bp_list},
    {"/pro/*", Uri::pro},
    {"/pro", Uri::pro_list},
    {"/brs/*", Uri::brs},
    {"/brs", Uri::brs_list},
    {"/br/*", Uri::br},
    {"/br", Uri::br_list},
    {"/tar/*", Uri::tar},
    {"/tar", Uri::tar_list},
    {"/ver/*", Uri::ver},
    {"/ver", Uri::ver_list},
    {"/ss", Uri::ss},
    {"/ppy/*", Uri::ppy},
    {"/ppy", Uri::ppy_list},
    {"/ab", Uri::ab},
    {"/os", Uri::os},
    {"/actsi/*", Uri::actsi},
    {"/actsi", Uri::actsi_list},
    {"/si/*", Uri::si},
    {"/si", Uri::si_list},
    {"/cr/*", Uri::cr},
    {"/cr", Uri::cr_list},
    {"/frq/*", Uri::frq},
    {"/frq", Uri::frq_list},
    {"/frp/*", Uri::frp},
    {"/frp", Uri::frp_list},
    {"/der/*", Uri::der},
    {"/der", Uri::der_list},
    {"/aupt", Uri::aupt},
    {"/derp/*", Uri::derp},
    {"/derp", Uri::derp_list},
    {"/cdp", Uri::cdp},
    {"/derg", Uri::derg},
    {"/ders", Uri::ders},
    {"/dera", Uri::dera},
    {"/dercap", Uri::dercap},
    {"/actderc/*", Uri::actderc},
    {"/actderc", Uri::actderc_list},
    {"/derc", Uri::derc},
    {"/dderc", Uri::dderc},
    {"/dc/*", Uri::dc},
    {"/dc", Uri::dc_list}
};

#endif // __URI_H__